name: Docker Image CI (Upload Tag) # Name of the workflow

on: # Set the event that will trigger the workflow
  push: # Push event
    tags: # Push event tag
      - 'v*' # Push event tag pattern

jobs: # Set a job

  build: # Set the job name

    runs-on: ubuntu-latest # Set the job to run on the latest version of Ubuntu

    steps: # Set the job steps
    - name: Checkout # Set the step name
      uses: actions/checkout@v3 # Use the checkout action
      
    - name: Set up QEMU # For ARM support
      uses: docker/setup-qemu-action@v2 # Use the setup-qemu action
      
    - name: Buildx # For ARM support
      uses: docker/setup-buildx-action@v2 # Use the setup-buildx action
      
    -
      name: Docker meta # Set the step name
      id: meta # Set an id for the step
      uses: docker/metadata-action@v4 # Use the metadata-action action
      with: # Set the input parameter
        images: amirpourmand/al-folio # Set the image name

    - name: Login # Set the step name
      uses: docker/login-action@v2 # Use the login-action action
      with: # Set the input parameter
        username: ${{ secrets.DOCKER_USERNAME }} # Use the secrets.DOCKER_USERNAME secret
        password: ${{ secrets.DOCKER_PASSWORD }} # Use the secrets.DOCKER_PASSWORD secret

    - name: Build and push # Set the step name
      uses: docker/build-push-action@v3 # Use the build-push-action action
      with: # Set the input parameter
        context: . # Set the build context
        platforms: linux/amd64,linux/arm64/v8 # Set the platforms
        push: ${{ github.event_name != 'pull_request' }} # Push the image if the event is not pull_request
        tags: ${{ steps.meta.outputs.tags }} # Use the tags output from the meta step
        labels: ${{ steps.meta.outputs.labels }} # Use the labels output from the meta step

